
import trabalhobd.ButtonColumn;
import java.awt.Button;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.EventObject;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableModel;
import trabalhobd.DBConnector;
import trabalhobd.DataManipulation;
import trabalhobd.DataSelection;
import trabalhobd.ErrorTranslator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

class myEditor extends DefaultCellEditor {
    public myEditor(JCheckBox checkBox) {
        super(checkBox);
    }
    @Override
    public boolean isCellEditable(EventObject anEvent) {
        return false;
    }
}

/**
 *
 * @author leonardo
 */
public class DBGUI extends javax.swing.JFrame {
    public static String[] estados = {"AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"};
    public DataManipulation dml;
    public DataSelection ds;
    
    /**
     * Creates new form DBGUI
     */
    public DBGUI() {
        initComponents();
        estadoZonaCria.setModel(new javax.swing.DefaultComboBoxModel(estados));
        
        try{
            DBConnector connector = new DBConnector("a7987265", "a7987265", true);
            if (!connector.test()){
                JOptionPane.showMessageDialog(null, "Problemas com a conexão.\n");
                return;
            }
            System.out.println("Conexão efetuada.");
            
            this.dml = new DataManipulation(connector);
            this.ds = new DataSelection(connector);
        }catch(SQLException e1){
            JOptionPane.showMessageDialog(null, "Problemas ao iniciar programa.\n"+e1.getMessage());
            return;
        } catch (ClassNotFoundException e2) {
            JOptionPane.showMessageDialog(null, "Problemas ao iniciar programa.\n"+e2.getMessage());
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        registroPane = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        zonaPane = new javax.swing.JTabbedPane();
        inserePane = new javax.swing.JPanel();
        CriaPane = new javax.swing.JPanel();
        nroZonaLabelCria = new javax.swing.JLabel();
        numeroZonaCria = new javax.swing.JSpinner();
        estadoZonaLabelCria = new javax.swing.JLabel();
        estadoZonaCria = new javax.swing.JComboBox();
        endZonaLabelCria = new javax.swing.JLabel();
        enderecoZonaCria = new javax.swing.JTextField();
        insereZonaBotaoCria = new javax.swing.JButton();
        consultaPane = new javax.swing.JPanel();
        nroZonaLabel2 = new javax.swing.JLabel();
        numeroZona2 = new javax.swing.JSpinner();
        atualizaZona = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaZona = new javax.swing.JTable();
        secaoPane = new javax.swing.JPanel();
        urnaPane = new javax.swing.JPanel();
        pessoasPane = new javax.swing.JTabbedPane();
        votosPane = new javax.swing.JTabbedPane();
        relatoriosPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nroZonaLabelCria.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nroZonaLabelCria.setText("Número da Zona Eleitoral*:");

        numeroZonaCria.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        numeroZonaCria.setToolTipText("min: 0 - max: 999");

        estadoZonaLabelCria.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        estadoZonaLabelCria.setText("Estado da Zona Eleitoral*:");

        estadoZonaCria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        estadoZonaCria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoZonaCriaActionPerformed(evt);
            }
        });

        endZonaLabelCria.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        endZonaLabelCria.setText("Endereço da Zona Eleitoral:");

        enderecoZonaCria.setToolTipText("max. num. characters: 200");

        insereZonaBotaoCria.setText("Insere");
        insereZonaBotaoCria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insereZonaBotaoCriaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CriaPaneLayout = new javax.swing.GroupLayout(CriaPane);
        CriaPane.setLayout(CriaPaneLayout);
        CriaPaneLayout.setHorizontalGroup(
            CriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CriaPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CriaPaneLayout.createSequentialGroup()
                        .addComponent(endZonaLabelCria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enderecoZonaCria))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CriaPaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(insereZonaBotaoCria))
                    .addGroup(CriaPaneLayout.createSequentialGroup()
                        .addGroup(CriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CriaPaneLayout.createSequentialGroup()
                                .addComponent(estadoZonaLabelCria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(estadoZonaCria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CriaPaneLayout.createSequentialGroup()
                                .addComponent(nroZonaLabelCria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numeroZonaCria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 522, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CriaPaneLayout.setVerticalGroup(
            CriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CriaPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nroZonaLabelCria)
                    .addComponent(numeroZonaCria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoZonaLabelCria)
                    .addComponent(estadoZonaCria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endZonaLabelCria)
                    .addComponent(enderecoZonaCria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insereZonaBotaoCria)
                .addContainerGap(351, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout inserePaneLayout = new javax.swing.GroupLayout(inserePane);
        inserePane.setLayout(inserePaneLayout);
        inserePaneLayout.setHorizontalGroup(
            inserePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inserePaneLayout.createSequentialGroup()
                .addComponent(CriaPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        inserePaneLayout.setVerticalGroup(
            inserePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CriaPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        zonaPane.addTab("Cria Nova", inserePane);

        nroZonaLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nroZonaLabel2.setText("Número da Zona Eleitoral:");

        numeroZona2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        numeroZona2.setToolTipText("min: 0 - max: 999");

        atualizaZona.setText("Procurar Dados");
        atualizaZona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizaZonaMouseClicked(evt);
            }
        });

        tabelaZona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número da Zona*", "Estado da Zona*", "Endereço da Zona", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaZona);
        if (tabelaZona.getColumnModel().getColumnCount() > 0) {
            tabelaZona.getColumnModel().getColumn(0).setMinWidth(110);
            tabelaZona.getColumnModel().getColumn(1).setMinWidth(110);
            tabelaZona.getColumnModel().getColumn(2).setMinWidth(363);
            tabelaZona.getColumnModel().getColumn(3).setMinWidth(90);
            tabelaZona.getColumnModel().getColumn(4).setMinWidth(90);
        }

        javax.swing.GroupLayout consultaPaneLayout = new javax.swing.GroupLayout(consultaPane);
        consultaPane.setLayout(consultaPaneLayout);
        consultaPaneLayout.setHorizontalGroup(
            consultaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atualizaZona)
                .addGap(1130, 1130, 1130)
                .addComponent(nroZonaLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroZona2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(consultaPaneLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        consultaPaneLayout.setVerticalGroup(
            consultaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nroZonaLabel2)
                    .addComponent(numeroZona2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizaZona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        zonaPane.addTab("Consulta", consultaPane);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zonaPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zonaPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        registroPane.addTab("Zona", jPanel3);

        javax.swing.GroupLayout secaoPaneLayout = new javax.swing.GroupLayout(secaoPane);
        secaoPane.setLayout(secaoPaneLayout);
        secaoPaneLayout.setHorizontalGroup(
            secaoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        secaoPaneLayout.setVerticalGroup(
            secaoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        registroPane.addTab("Seção", secaoPane);

        javax.swing.GroupLayout urnaPaneLayout = new javax.swing.GroupLayout(urnaPane);
        urnaPane.setLayout(urnaPaneLayout);
        urnaPaneLayout.setHorizontalGroup(
            urnaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        urnaPaneLayout.setVerticalGroup(
            urnaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        registroPane.addTab("Urna", urnaPane);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registroPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registroPane)
        );

        MainPane.addTab("Registro", jPanel1);
        MainPane.addTab("Pessoas", pessoasPane);
        MainPane.addTab("Votos", votosPane);
        MainPane.addTab("Relatórios", relatoriosPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizaZonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizaZonaMouseClicked
        ResultSet res;
        try {
            res = ds.selectAllZonas();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problemas ao selecionar Zonas Eleitorais.\n"+ErrorTranslator.translate(ex.getErrorCode()));
            return;
        }
        DefaultTableModel model = new myTableModel(new int[]{0, 0, 1, 1, 1});
        model.setColumnIdentifiers(new String[] {tabelaZona.getModel().getColumnName(0),
        tabelaZona.getModel().getColumnName(1),
        tabelaZona.getModel().getColumnName(2),
        tabelaZona.getModel().getColumnName(3),
        tabelaZona.getModel().getColumnName(4)});

        Action save = new AbstractAction("-") {
            @Override
            public void actionPerformed(ActionEvent e) {
                JTable table = (JTable) e.getSource();
                int row = Integer.valueOf(e.getActionCommand());
                try {
                    dml.updateZona((int)tabelaZona.getValueAt(row, 0), (String)tabelaZona.getValueAt(row, 1), (String)tabelaZona.getValueAt(row, 2));
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Problemas ao atualizar Zona Eleitoral.\n"+ErrorTranslator.translate(ex.getErrorCode()));
                }
            }
        };
        Action delete = new AbstractAction("-") {
            @Override
            public void actionPerformed(ActionEvent e) {
                JTable table = (JTable) e.getSource();
                int row = Integer.valueOf(e.getActionCommand());
                try {
                    dml.deleteZona((int)tabelaZona.getValueAt(row, 0), (String)tabelaZona.getValueAt(row, 1));
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Problemas ao deletar Zona Eleitoral.\n"+ErrorTranslator.translate(ex.getErrorCode()));
                }
            }
        };

        tabelaZona.setModel(model);
        try {
            for(int i=0; res.next(); i++)
                model.addRow(new Object[]{res.getInt(1), res.getString(2), res.getString(3), "Salvar", "Deletar"});
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problemas ao criar tabela.\n"+ErrorTranslator.translate(ex.getErrorCode()));
        }
        ButtonColumn colunaSalvar = new ButtonColumn(tabelaZona, save, 3);
        ButtonColumn deletarSalvar = new ButtonColumn(tabelaZona, delete, 4);
        tabelaZona.getColumn(model.getColumnName(0)).setMinWidth(110);
        tabelaZona.getColumn(model.getColumnName(1)).setMinWidth(100);
        tabelaZona.getColumn(model.getColumnName(2)).setMinWidth(363);
        tabelaZona.getColumn(model.getColumnName(3)).setMinWidth(90);
        tabelaZona.getColumn(model.getColumnName(4)).setMinWidth(90);
        //tabelaZona.setModel(model);
        //} catch (SQLException ex) {
        //    JOptionPane.showMessageDialog(null, "Problemas ao executar consulta.\n"+ErrorTranslator.translate(ex.getErrorCode()));
        //}
    }//GEN-LAST:event_atualizaZonaMouseClicked

    private void insereZonaBotaoCriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insereZonaBotaoCriaMouseClicked
        try {
            dml.insereZona((int)numeroZonaCria.getValue(), (String)estadoZonaCria.getSelectedItem(), (String)enderecoZonaCria.getText());
            JOptionPane.showMessageDialog(null, "Valor inserido com sucesso.\n");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problemas ao inserir Zona Eleitoral.\n"+ErrorTranslator.translate(ex.getErrorCode()));
        }
    }//GEN-LAST:event_insereZonaBotaoCriaMouseClicked

    private void estadoZonaCriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoZonaCriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoZonaCriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBGUI().setVisible(true);
            }
        });
                
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CriaPane;
    private javax.swing.JTabbedPane MainPane;
    private javax.swing.JButton atualizaZona;
    private javax.swing.JPanel consultaPane;
    private javax.swing.JLabel endZonaLabelCria;
    private javax.swing.JTextField enderecoZonaCria;
    private javax.swing.JComboBox estadoZonaCria;
    private javax.swing.JLabel estadoZonaLabelCria;
    private javax.swing.JPanel inserePane;
    private javax.swing.JButton insereZonaBotaoCria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nroZonaLabel2;
    private javax.swing.JLabel nroZonaLabelCria;
    private javax.swing.JSpinner numeroZona2;
    private javax.swing.JSpinner numeroZonaCria;
    private javax.swing.JTabbedPane pessoasPane;
    private javax.swing.JTabbedPane registroPane;
    private javax.swing.JTabbedPane relatoriosPane;
    private javax.swing.JPanel secaoPane;
    private javax.swing.JTable tabelaZona;
    private javax.swing.JPanel urnaPane;
    private javax.swing.JTabbedPane votosPane;
    private javax.swing.JTabbedPane zonaPane;
    // End of variables declaration//GEN-END:variables

    private static class myTableModel  extends DefaultTableModel{
        private int[] iseditable;
        public myTableModel(int[] iseditable){
            super();
            this.iseditable = iseditable;
        }
        public boolean isCellEditable(int row, int column) {
            if (iseditable[column] == 1){
               return true;
            }else{
               return false;
            }
        }
    }
}
