
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import trabalhobd.DBConnector;
import trabalhobd.DataManipulation;
import trabalhobd.DataSelection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author leonardo
 */
public class DBGUI extends javax.swing.JFrame {
    public static String[] estados = {"AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO"};
    public DataManipulation dml;
    public DataSelection ds;
    
    /**
     * Creates new form DBGUI
     */
    public DBGUI() {
        initComponents();
        estadoZona.setModel(new javax.swing.DefaultComboBoxModel(estados));
        
        try{
            DBConnector connector = new DBConnector("a7987265", "a7987265", true);
            if (!connector.test()){
                JOptionPane.showMessageDialog(null, "Problemas com a conexão.\n");
                return;
            }
            System.out.println("Conexão efetuada.");
            
            this.dml = new DataManipulation(connector);
            this.ds = new DataSelection(connector);
        }catch(SQLException e1){
            JOptionPane.showMessageDialog(null, "Problemas ao iniciar programa.\n"+e1.getMessage());
            return;
        } catch (ClassNotFoundException e2) {
            JOptionPane.showMessageDialog(null, "Problemas ao iniciar programa.\n"+e2.getMessage());
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        registroPane = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        zonaPane = new javax.swing.JTabbedPane();
        inserePane = new javax.swing.JPanel();
        CriaPane = new javax.swing.JPanel();
        nroZonaLabel1 = new javax.swing.JLabel();
        numeroZona1 = new javax.swing.JSpinner();
        estadoZonaLabel1 = new javax.swing.JLabel();
        estadoZona = new javax.swing.JComboBox();
        endZonaLabel1 = new javax.swing.JLabel();
        enderecoZona1 = new javax.swing.JTextField();
        insereZonaBotao1 = new javax.swing.JButton();
        inserePane2 = new javax.swing.JPanel();
        nroZonaLabel2 = new javax.swing.JLabel();
        numeroZona2 = new javax.swing.JSpinner();
        atualizaZona = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaZona = new javax.swing.JTable();
        secaoPane = new javax.swing.JPanel();
        urnaPane = new javax.swing.JPanel();
        pessoasPane = new javax.swing.JTabbedPane();
        votosPane = new javax.swing.JTabbedPane();
        relatoriosPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nroZonaLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nroZonaLabel1.setText("Número da Zona Eleitoral:");

        numeroZona1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        numeroZona1.setToolTipText("min: 0 - max: 999");

        estadoZonaLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        estadoZonaLabel1.setText("Estado da Zona Eleitoral:");

        estadoZona.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        estadoZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoZonaActionPerformed(evt);
            }
        });

        endZonaLabel1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        endZonaLabel1.setText("Endereço da Zona Eleitoral:");

        enderecoZona1.setToolTipText("max. num. characters: 200");

        insereZonaBotao1.setText("Insere");
        insereZonaBotao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insereZonaBotao1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CriaPaneLayout = new javax.swing.GroupLayout(CriaPane);
        CriaPane.setLayout(CriaPaneLayout);
        CriaPaneLayout.setHorizontalGroup(
            CriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CriaPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CriaPaneLayout.createSequentialGroup()
                        .addComponent(endZonaLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enderecoZona1))
                    .addGroup(CriaPaneLayout.createSequentialGroup()
                        .addGroup(CriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(CriaPaneLayout.createSequentialGroup()
                                .addComponent(nroZonaLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numeroZona1))
                            .addGroup(CriaPaneLayout.createSequentialGroup()
                                .addComponent(estadoZonaLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(estadoZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 529, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CriaPaneLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(insereZonaBotao1)))
                .addContainerGap())
        );
        CriaPaneLayout.setVerticalGroup(
            CriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CriaPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nroZonaLabel1)
                    .addComponent(numeroZona1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoZonaLabel1)
                    .addComponent(estadoZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CriaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endZonaLabel1)
                    .addComponent(enderecoZona1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insereZonaBotao1)
                .addContainerGap(351, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout inserePaneLayout = new javax.swing.GroupLayout(inserePane);
        inserePane.setLayout(inserePaneLayout);
        inserePaneLayout.setHorizontalGroup(
            inserePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inserePaneLayout.createSequentialGroup()
                .addComponent(CriaPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        inserePaneLayout.setVerticalGroup(
            inserePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CriaPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        zonaPane.addTab("Cria", inserePane);

        nroZonaLabel2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nroZonaLabel2.setText("Número da Zona Eleitoral:");

        numeroZona2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        numeroZona2.setToolTipText("min: 0 - max: 999");

        atualizaZona.setText("Atualiza Dados");
        atualizaZona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                atualizaZonaMouseClicked(evt);
            }
        });

        tabelaZona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número da Zona", "Estado da Zona", "Endereço da Zona", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaZona);
        if (tabelaZona.getColumnModel().getColumnCount() > 0) {
            tabelaZona.getColumnModel().getColumn(0).setMaxWidth(100);
            tabelaZona.getColumnModel().getColumn(1).setMaxWidth(100);
            tabelaZona.getColumnModel().getColumn(2).setMaxWidth(600);
            tabelaZona.getColumnModel().getColumn(3).setMaxWidth(100);
            tabelaZona.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        javax.swing.GroupLayout inserePane2Layout = new javax.swing.GroupLayout(inserePane2);
        inserePane2.setLayout(inserePane2Layout);
        inserePane2Layout.setHorizontalGroup(
            inserePane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inserePane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atualizaZona)
                .addGap(1138, 1138, 1138)
                .addComponent(nroZonaLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroZona2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(inserePane2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        inserePane2Layout.setVerticalGroup(
            inserePane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inserePane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inserePane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nroZonaLabel2)
                    .addComponent(numeroZona2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atualizaZona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        zonaPane.addTab("Consulta", inserePane2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zonaPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zonaPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        registroPane.addTab("Zona", jPanel3);

        javax.swing.GroupLayout secaoPaneLayout = new javax.swing.GroupLayout(secaoPane);
        secaoPane.setLayout(secaoPaneLayout);
        secaoPaneLayout.setHorizontalGroup(
            secaoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        secaoPaneLayout.setVerticalGroup(
            secaoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        registroPane.addTab("Seção", secaoPane);

        javax.swing.GroupLayout urnaPaneLayout = new javax.swing.GroupLayout(urnaPane);
        urnaPane.setLayout(urnaPaneLayout);
        urnaPaneLayout.setHorizontalGroup(
            urnaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        urnaPaneLayout.setVerticalGroup(
            urnaPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        registroPane.addTab("Urna", urnaPane);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registroPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registroPane)
        );

        MainPane.addTab("Registro", jPanel1);
        MainPane.addTab("Pessoas", pessoasPane);
        MainPane.addTab("Votos", votosPane);
        MainPane.addTab("Relatórios", relatoriosPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estadoZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoZonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoZonaActionPerformed

    private void insereZonaBotao1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insereZonaBotao1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_insereZonaBotao1MouseClicked

    private void atualizaZonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atualizaZonaMouseClicked
        try {
            ResultSet res = ds.selectAllZonas();
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[] {tabelaZona.getModel().getColumnName(0),tabelaZona.getModel().getColumnName(1),tabelaZona.getModel().getColumnName(2)});
            tabelaZona.setModel(model);
            System.out.println("Select All Zonas:");
            for(int i=0; res.next(); i++){
                model.addRow(new Object[]{res.getInt(1), res.getString(2), res.getString(3), });
                System.out.println(res.getInt(1)+" "+res.getString(2)+" "+res.getString(3));
            }
            System.out.println("All Zonas retornadas.");
            //tabelaZona.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Problemas ao executar consulta.\n"+ex.getMessage());
        }
    }//GEN-LAST:event_atualizaZonaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBGUI().setVisible(true);
            }
        });
                
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CriaPane;
    private javax.swing.JTabbedPane MainPane;
    private javax.swing.JButton atualizaZona;
    private javax.swing.JLabel endZonaLabel1;
    private javax.swing.JTextField enderecoZona1;
    private javax.swing.JComboBox estadoZona;
    private javax.swing.JLabel estadoZonaLabel1;
    private javax.swing.JPanel inserePane;
    private javax.swing.JPanel inserePane2;
    private javax.swing.JButton insereZonaBotao1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nroZonaLabel1;
    private javax.swing.JLabel nroZonaLabel2;
    private javax.swing.JSpinner numeroZona1;
    private javax.swing.JSpinner numeroZona2;
    private javax.swing.JTabbedPane pessoasPane;
    private javax.swing.JTabbedPane registroPane;
    private javax.swing.JTabbedPane relatoriosPane;
    private javax.swing.JPanel secaoPane;
    private javax.swing.JTable tabelaZona;
    private javax.swing.JPanel urnaPane;
    private javax.swing.JTabbedPane votosPane;
    private javax.swing.JTabbedPane zonaPane;
    // End of variables declaration//GEN-END:variables
}
